<?php

/**
 * Implements hook_patterns_components().
 *
 * Tell the Patterns engine where the components are.
 */
function patterns_patterns_components() {
  return drupal_get_path('module', 'patterns_components') . '/components/';
}

/**
 * 
 * Auxiliar function that can be used by the components to check if the action
 * has all the expected mandatory values.
 * 
 * @param array $attributes  List of attributes in the current action
 * @param array $mandatory_attributes  List of expected mandatory attributes
 * @param string $msg  Message that will be promted to the user
 * @return boolean  Returns TRUE if all the $mandatory_attributes are found in $attributes, FALSE otherwise
 */
function _has_all_mandatory_attributes($attributes, $mandatory_attributes, &$msg) {
  $result = TRUE;
  foreach ($mandatory_attributes as $att){
    if (!array_key_exists($att, $attributes)) {
      $msg .= t('Mandatory attribute %att could not be found.', array('%att' =>'name',));
      $result = FALSE;
    }
  }
  return $result;
}
